version: 2
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/angular2cesium
    steps:
      - checkout
      - run:
        name: Pre-Dependencies
        command: mkdir ~/angular2cesium/artifacts
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: NPM lint
          command: npm run lint
      - store_artifacts:
          path: ~/angular2cesium/artifacts