version: 2
jobs:
  build:
    docker:
      - image: zenika/alpine-chrome:with-node
    working_directory: ~/angular-cesium
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: mkdir -p ~/angular-cesium/artifacts
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Lint
          command: npm run lint
      - run:
          name: Run tests
          command: npm run test:ci
      - run:
          name: Run bundle
          command: npm run lib:build
      - store_artifacts:
          path: ~/angular-cesium/dist
